import { z } from "zod";

// universal for string with optional func
export const optionalString = z.string().trim().optional().or(z.literal(""));

// general infro schema  and type
export const generalInfoSchema = z.object({
  title: optionalString,
  description: optionalString,
  templateNo: z.number().optional(),
});
export type GeneralInfoValues = z.infer<typeof generalInfoSchema>;

// perseon infor schema  and type
export const personalInfoSchema = z.object({
  photo: z
    .custom<File | undefined>()
    .refine(
      (file) =>
        !file || (file instanceof File && file.type.startsWith("image/")),
      "Must be an image file",
    )
    .refine(
      (file) => !file || file.size <= 1024 * 1024 * 4,
      "File must be less than 4MB",
    ),
  firstName: optionalString,
  middleName: optionalString,
  lastName: optionalString,
  jobTitle: optionalString,
  city: optionalString,
  country: optionalString,
  phone: optionalString,
  email: optionalString,
  request_order_id: optionalString,
  paid_order_id: optionalString,
  isDownloaded: z.boolean(),
  Payment_status: z.boolean(),
  enable_edit: z.boolean(),
});

export type PersonalInfoValues = z.infer<typeof personalInfoSchema>;

// work exprience schema  and type
export const workExperienceSchema = z.object({
  workExperiences: z
    .array(
      z.object({
        position: optionalString,
        company: optionalString,
        startDate: optionalString,
        endDate: optionalString,
        description: optionalString,
      }),
    )
    .optional(),
});

export type WorkExperienceValues = z.infer<typeof workExperienceSchema>;

export type WorkExperience = NonNullable<
  z.infer<typeof workExperienceSchema>["workExperiences"]
>[number];

// education background schema  and type
export const educationSchema = z.object({
  educations: z
    .array(
      z.object({
        degree: optionalString,
        school: optionalString,
        startDate: optionalString,
        endDate: optionalString,
      }),
    )
    .optional(),
});

export type EducationValues = z.infer<typeof educationSchema>;

// skills schema   and type
export const skillsSchema = z.object({
  skills: z.array(z.string().trim()).optional(),
});

export type SkillsValues = z.infer<typeof skillsSchema>;

// professiona summaryschema  and type
export const summarySchema = z.object({
  summary: optionalString,
});
export type SummaryValues = z.infer<typeof summarySchema>;

// language profiency  && type
export const languageSchema = z.object({
  languages: z.array(z.string().trim()).optional(),
});
export type LanguagesValues = z.infer<typeof languageSchema>;

//reference schema and type
export const referenceSchema = z.object({
  references: z
    .array(
      z.object({
        referenceFirstName: optionalString,
        referenceLastName: optionalString,
        referenceJobTitle: optionalString,
        referenceCompanyName: optionalString,
        referenceAddress: optionalString,
        referencePhone: optionalString,
        referenceEmail: optionalString,
        referenceDescription: optionalString,
      }),
    )
    .optional(),
});
export type ReferenceValues = z.infer<typeof referenceSchema>;

// all resume schema and type
export const resumeSchema = z.object({
  ...generalInfoSchema.shape,
  ...personalInfoSchema.shape,
  ...workExperienceSchema.shape,
  ...educationSchema.shape,
  ...skillsSchema.shape,
  ...languageSchema.shape,
  ...referenceSchema.shape,
  ...summarySchema.shape,
  colorHex: optionalString,
  borderStyle: optionalString,
});

export type ResumeValues = Omit<z.infer<typeof resumeSchema>, "photo"> & {
  id?: string;
  photo?: File | string | null;
};

// work exprience generated bya ai schema and type
export const generateWorkExperienceSchema = z.object({
  description: z
    .string()
    .trim()
    .min(1, "Required")
    .min(20, "Must be at least 20 characters"),
});

export type GenerateWorkExperienceInput = z.infer<
  typeof generateWorkExperienceSchema
>;

// summary generate by ai schema and type
export const generateSummarySchema = z.object({
  jobTitle: optionalString,
  ...workExperienceSchema.shape,
  ...educationSchema.shape,
  ...skillsSchema.shape,
});

export type GenerateSummaryInput = z.infer<typeof generateSummarySchema>;

export type PaymentOptionsType = {
  customerName: string;
  customerEmail: string;
  amountToCharge: number;
  customerPhoneNumber: string;
};

export type RequestResponseType = {
  message: unknown;
  success: boolean;
};

export type ZenoPayOptionsType = {
  apiKey: string;
  secretKey: string;
  accountID: string;
};